name: build-macos
on:
  pull_request:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - .github/workflows/build-macos.yml
  push:
    branches: main
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - .github/workflows/build-macos.yml
jobs:
  macos:
    name: build-on-macos
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.5.1

      - name: cargo build
        shell: bash
        run: |
          cargo build --all
