on:
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-clippy.yml
      - 'rust-toolchain'
      - 'rust-toolchain.toml'
  pull_request:
    paths:
      - '**.rs'
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-clippy.yml
      - 'rust-toolchain'
      - 'rust-toolchain.toml'
name: cargo clippy
jobs:
  cargoclippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.9.2

      - name: Install ffmpeg
        run: |
          sudo apt update
          sudo apt install \
            ffmpeg \
            libavformat-dev \
            libavutil-dev \
            libclang-dev \
            libswscale-dev \
            --no-install-recommends

      - name: Run clippy
        run: cargo clippy --workspace --examples --tests --benches --all-features -- -D warnings
