on:
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-build.yml
      - 'rust-toolchain'
      - 'rust-toolchain.toml'
  pull_request:
    paths:
      - '**.rs'
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-build.yml
      - 'rust-toolchain'
      - 'rust-toolchain.toml'
name: cargo build
jobs:
  cargobuild:
    name: cargo build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.5.1

      - name: Install ffmpeg
        run: |
          sudo apt update
          sudo apt install \
            ffmpeg \
            libavformat-dev \
            libavutil-dev \
            libclang-dev \
            --no-install-recommends

      - name: Run cargo build
        run: |
          cargo build --all
        shell: bash
